# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 75aa80b96077b7b8b445e7d10d1aa77b0aafdb7fe6fc9262421c230877246669673c36f0b556aa2d35a5ff597800f9807327a952d2a0f2969780548dcbd37ef5

test:
  secret_key_base: d0522e3a28a2e43947a5c5eff657e1d841b2eca30ca2fddc7301f13def0f1cf815059f9db61b533fa16aba36179fa9e3d76fce5ec464bbc1658f6ee035e0f778

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
